### ISSUE TITLE
[FEAT] Change owner of web files to PUID

### ISSUE THREAD

**Issue by raphpa** [linuxserver/docker-jellyfin#182]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Changing the owner of the included web interface files to the given PUID/PGID that jellyfin runs with.

### Reason for change

The plugin [Jellyscrub](https://github.com/nicknsy/jellyscrub/) needs a custom script on the player page to work. For that it injects itself into the index.html file on jellyfin start. 
This only works if the container is started with root for PUID/PGID, else the jellyfin process is not allowed to modify the index.html file.

### Proposed code change

Changing the owner of /usr/share/jellyfin/web to PUID/PGID on container start.

**Comment by marouamghar** [comment]
I suppose a chmod after creating the files would fix the issue!

**Comment by Silvenga** [comment]
@raphpa @marouamghar created a pr for this. I believe this would fully resolve your pain points?

**Comment by marouamghar** [comment]
@Silvenga i think so. I looked at the PR, are you planning on converting it to a mod?

**Comment by raphpa** [comment]
Not sure why chowning takes that much time, but a `RUN chmod -R 666 /usr/share/jellyfin/web` in `Dockerfile` would also satisfy the plugins' ability to inject itself.

**Comment by Silvenga** [comment]
TBH @marouamghar - I stopped using the LSIO image since I needed to debug the internals of JellyFin. I've built my own https://github.com/silvenga-docker/jellyfin-debug.

Through this, I've separated the frontend and backend and I'm having Nginx rewrite the index.html file to inject the script in.

https://github.com/silvenga-docker/jellyfin-debug/blob/85a17a83f54fe3e0d02dc51b442a296c2aec20cd/src/jellyfin-web/rootfs/etc/nginx/conf.d/default.conf#L6-L14
