### ISSUE TITLE
[FEAT] Make the web files be owned by PUID / PGID

### ISSUE THREAD

**Issue by Ulrar** [linuxserver/docker-jellyfin#253]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I see this was already requested in https://github.com/linuxserver/docker-jellyfin/issues/182 but closed for inactivity.

I'd be great to chown the /usr/share/jellyfin/web/ folder to abc:abc, so that plugins like intro-skipper and others that require adding their own files to that folder can be installed. I've tested it, and `chown abc:abc -R /usr/share/jellyfin/web/` does the trick.

### Reason for change

I'm using https://github.com/jumoog/intro-skipper which needs to be able to make changes to that folder to work

### Proposed code change

In the dockerfile: 
```
RUN chown abc:abc -R /usr/share/jellyfin/web/
```

**Comment by thespad** [comment]
We try and avoid chowning the container filesystem, especially large directories, because of an overlayfs big that can cause extremely slow chown performance on some devices. We can't chown it at build tone because we don't know the uid/gid of the ABC user at that point. 

You can use our [customisation](https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers) logic to perform the chown in your container
