### ISSUE TITLE
How to map entire folder to container

### ISSUE THREAD

**Issue by LegendaryB** [linuxserver/docker-jellyfin#6]
Hey I was just wondering how I could map 1 entire media folder?
Instead of mapping tv series folder, movie folder etc. separately

**Comment by aptalca** [comment]
just map your folder with `-v /your/folder:/media` and in jellyfin, browse to `/media`

**Comment by crypdick** [comment]
> just map your folder with `-v /your/folder:/media` and in jellyfin, browse to `/media`

Don't you mean `-v /your/folder:/data`

**Comment by aptalca** [comment]
It doesn't really matter what it is mapped as inside the container as long as the user uses the same endpoint in the jellyfin gui to look for the files (and also as long as there isn't already an existing crucial folder inside the container at the same endpoint, because then it would be wiped out)

The only in-container endpoint that shouldn't be modified in this case is `/config`
